pygments: true
highlighter: rouge
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Shankai Ji
production_url : http://jishankai.cn
description: "Somethings by Shankai Ji."
disqus_shortname: skjiblog
analytics: UA-47846061-1
gauges: 52f36bdf92c6ac4a7b0008e0
author :
  name : Shankai Ji
  github : skji
  twitter : jishankai
  email: jishankai@qq.com
