markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Shankai Ji
production_url : http://skji.github.co
description: "Somethings by Shankai Ji."
disqus_shortname: skjiblog
analytics: UA-47846061-1
author :
  name : Shankai Ji
  github : skji
  twitter : jishankai
  email: jishankai@gmail.com
